name: Auto Approve Dependabot PRs
description: 'Automatically approves pull requests created by Dependabot'
inputs:
  token:
    description: 'GitHub token with approval permissions'
    required: true
  should-approve:
    description: 'should the workflow approve the PR'
    required: false
    default: true
  should-merge:
    description: 'should the workflow merge the PR'
    required: false
    default: true


runs:
  using: "composite"
  steps:
    - name: Check (trivial) actor context
      shell: bash
      run: |      
        if [[ "${{ github.actor }}" != "dependabot[bot]" ]] || \
        [[ "${{ github.event.pull_request.user.login }}" != "dependabot[bot]" ]] || \
        [[ "${{ github.event.pull_request.user.type }}" != "Bot" ]] || \
        [[ "${{ github.event_name }}" != "pull_request" ]]; then
          echo "This PR is not from Dependabot.\nFailing."
          exit 1
        fi

    - name: Verify that dependency update commit's signature is from Dependabot
      shell: bash
      run: |
        # Fetch commit information
        echo "Fetching commit information.."
        RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$REPO/commits/$COMMIT_SHA)
        
        if [ $? -ne 0 ]; then
          echo "Failed to fetch commit($COMMIT_SHA) details for the triggering PR.\nFailning."
          exit 1
        fi
        
        # Extract verification status and reason using jq
        VERIFIED=$(echo "$RESPONSE" | jq -r '.commit.verification.verified')
        REASON=$(echo "$RESPONSE" | jq -r '.commit.verification.reason')
        
        # Check if the commit is verified
        if [[ "$VERIFIED" != "true" || "$REASON" != "valid" ]]; then
          echo "Commit is not verified: $REASON. Failing."
          exit 1
        fi
      env:
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Approve and Merge PR
      shell: bash
      run: |
        
        if [ "${{ inputs.should-approve }}" = "true" ]; then
        
          REVIEWCOUNT=$(gh pr view $PR_URL --json reviews --jq '.reviews | length')
        
          if [ $? -ne 0 ]; then
            echo "Failed to fetch commit($COMMIT_SHA) details for the triggering PR.\nFailning."
            exit 1
          fi
        
          # hint: this does not check if the PAT token user approved the PR - just if there is approval already
          if [[ "$REVIEWCOUNT" -eq 0 ]]; then        
            echo "Approving PR..."
            gh pr review --approve --body "Auto-approved." "$PR_URL" 
          else
            echo "PR already approved."
          fi
        
        else
          echo "Skipping approval."
        fi

        if [ "${{ inputs.should-merge }}" = "true" ]; then
          echo "Merging PR..."
          gh pr merge --squash --auto "$PR_URL"
        else
          echo "Skipping merge."
        fi

      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ inputs.token }}