name: Deploy to Maven Central
description: Action to deploy a Maven project to Maven Central

inputs:
  java-distribution:
    description: 'The Java distribution to build the project'
    required: true
  java-version:
    description: 'Java version to build the project'
    required: true
  server-id:
    description: 'Id of the server to deploy to'
    required: true
  server-username:
    description: 'Username for authentication to Maven Central'
    required: true
  server-password:
    description: 'Password or token for authentication to Maven Central'
    required: true
  gpg-private-key:
    description: 'GPG private key to sign the deployed artefacts'
    required: true
  gpg-passphrase:
    description: 'GPG passphrase of the GPG private key'
    required: true
  mvn-cli-args:
    description: 'Arguments to add to the maven deploy command (default: "-DskipTests")'
    required: false
    default: '-DskipTests'
  deploy-mode:
    description: 'Mode for the deployment. Possible modes are "release" and "snapshot" (default: release)'
    required: false
    default: "release"
  version-check:
    description: 'Check whether the version to deploy is higher than the latest deployed version (default: false)'
    required: false
    default: 'false'
  gh-release:
    description: 'Adds a Tag and emits a Github Release'
    required: false
    default: 'true'
  create-version-increment-pr:
    description: 'creates a new Branch which adds -SNAPSHOT to the version and increments the patch version number'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Java and Credentials
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        server-id: ${{ inputs.server-id }}
        server-username: MAVEN_USERNAME                 # Env var that holds the central publisher user name
        server-password: MAVEN_CENTRAL_TOKEN            # Env var that holds the central publisher user token
        gpg-private-key: ${{ inputs.gpg-private-key }}  # Substituted with the value stored in the referenced secret
        gpg-passphrase: MAVEN_GPG_PASSPHRASE            # Env var that holds the key's passphrase

    # If we want to deploy a snapshot version, we have to make sure that the version ends with SNAPSHOT
    - name: Check SNAPSHOT Version
      if: ${{ inputs.deploy-mode == 'snapshot' }}
      shell: bash
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Detected version: $VERSION"
        if [[ "$VERSION" != *-SNAPSHOT ]]; then
          echo "Deploy mode is 'snapshot', but version is not a SNAPSHOT version"
          exit 1
        fi

    # If we want to deploy a release version, we have to make sure that the version does not end with SNAPSHOT
    - name: Check Release Version
      if: ${{ inputs.deploy-mode == 'release' }}
      shell: bash
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Detected version: $VERSION"
        if [[ "$VERSION" == *-SNAPSHOT ]]; then
          echo "Deploy mode is 'release', but version is a SNAPSHOT version"
          exit 1
        fi

    - name: Ensure the proposed new version is higher than the latest
      if: ${{ inputs.version-check == 'true' }}
      shell: bash
      run: |
        PROPOSED_NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        TMP_POM=$(mktemp)
        curl -H "Authorization: token ${{ inputs.token }}" \
              -H "Accept: application/vnd.github.v3.raw" \
              -O \
              https://api.github.com/repos/${{ github.repository }}/contents/pom.xml?ref=${{ github.ref_name }} \
              -o "$TMP_POM"
        LATEST_VERSION=$(mvn -f "$TMP_POM" help:evaluate -Dexpression=project.version -q -DforceStdout)
        rm "$TMP_POM"
        
        if [ "$(printf "%s\n%s" "$PROPOSED_NEW_VERSION" "$LATEST_VERSION" | sort -V | head -n1)" = "$PROPOSED_NEW_VERSION" ]; then
          echo "Proposed new version is lower than the latest version!"
          echo "$PROPOSED_NEW_VERSION <= $LATEST_VERSION"
          exit 1
        fi

    - name: Check if gpg key is (already) shared publicly
      shell: bash
      run: |
        MAIL=$(gpg --with-colons --list-secret-keys | awk -F: '$1=="uid"{match($10, /<([^>]+)>/, m); if (m[1]) print m[1]}')
        echo "publisher adddress: $MAIL"

        # skip checks if more than one email address is found  
        EMAIL_COUNT=$(echo "$MAIL" | wc -l)
        if [[ "$EMAIL_COUNT" -eq 1 ]]; then
          if [[ -z "$MAIL" ]]; then
            echo "Error: Could not retrieve publisher email address from key." >&2
            exit 2
          fi
  
          # Searching for publicly shared PGP key 
          if ! gpg --batch --keyserver keys.openpgp.org --search-keys "$MAIL" >/dev/null 2>&1 ; then
            echo "Error: No PGP key found for $MAIL" >&2
            echo "Make sure the public key is published and email-verified on keys.openpgp.org" >&2
            exit 1
          fi
        else
          echo "Found $EMAIL_COUNT email address(es) - expected exactly 1 to verify if the key is shared publicly."
        fi


    - name: Run Maven Command
      shell: bash
      run: |
        # -U force updates just to make sure we are using latest dependencies
        # -B Batch mode (do not ask for user input), just in case
        mvn clean deploy -U -B ${{ inputs.mvn-cli-args }}
      env:
        MAVEN_USERNAME: ${{ inputs.server-username }}
        MAVEN_CENTRAL_TOKEN: ${{ inputs.server-password }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}

    - name: Create GitHub release
      if: ${{ inputs.gh-release == 'true' }}
      shell: bash
      # create new gh-release with .jar and its signature
      run: |
        echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        gh release create "${{ env.tag }}" \
        --title "${{ env.tag }}" \
        --generate-notes \
        target/*.jar \
        target/*.asc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create branch+PR which updates to next SNAPSHOT version
      if: ${{ inputs.create-version-increment-pr == 'true' }}
      shell: bash
      run: |
        BRANCH_NAME="increment_version_${{ github.sha }}"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b ${BRANCH_NAME} master
        mvn versions:set versions:commit -DnextSnapshot
        git ls-files | grep 'pom.xml$' | xargs git add
        git commit --allow-empty -am "Update version to next SNAPSHOT"
        git push origin ${BRANCH_NAME}
        gh pr create --draft -B develop -H ${BRANCH_NAME} -t "Update to next SNAPSHOT version" -b "Update to next SNAPSHOT version"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
