name: Documentation Preview

on:
  workflow_call:
    inputs:
      token:
        description: 'GitHub token for authentication'
        required: true
        type: string
      preview-name:
        description: 'The name of the preview'
        required: true
        type: string
      preview-title:
        description: 'The title of the preview'
        required: true
        type: string
      gh-pages-branch:
        description: 'The branch name where the gh pages are deployed to (default: gh-pages)'
        required: false
        default: 'gh-pages'
        type: string
      enable-comment:
        description: 'If true a comment with a link to the preview is added to the PR (default: true)'
        required: false
        default: 'true'
        type: string

jobs:
  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mike mkdocs-material mkdocs-tooltips git+https://github.com/RedisLabs/mkdocs-include.git git+https://github.com/swissiety/LspLexer4Pygments.git

      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy the Preview
        run: mike deploy --branch ${{ inputs.gh-pages-branch }} --push --update-aliases -t "${{ inputs.preview-title }}" ${{ inputs.preview-name }}

      - name: Comment Link to Preview
        if: inputs.enable-comment == 'true' && github.event.action != 'closed'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Detected changes in documentation files: [Documentation Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ inputs.preview-name }}/)

      - name: Delete the Preview
        if: github.event.action == 'closed'
        run: mike delete --push ${{ inputs.preview-name }}