name: Documentation Preview
description: handle preview of the documentation

inputs:
  title:
    description: 'The title of the preview - as shown on the version selector'
    required: false
    default: ''         # if not set we use the pr number
  pages-branch:
    description: 'The branch name where the gh pages are deployed to (default: gh-pages)'
    required: false
    default: 'gh-pages'
  enable-comment:
    description: 'If true a comment with a link to the preview is added to the PR (default: true)'
    required: false
    default: 'true'
  latest-directory:
    description: 'latest version to find the changed pages'
    required: false
    default: 'latest'
  docs-dir:
    description: 'same as in mkdocs.yml'
    required: false
    default: 'docs'
  pip_dependencies:
    description: 'install additional plugins for mkdocs'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Configuration
      shell: bash
      run: |
        echo "name=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "base-url=https://${OWNER}.github.io/${REPO}" >> $GITHUB_ENV
        
        if [ -z "${TITLE}" ]; then
          echo "title=Preview for PR-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        else
          echo "title=${TITLE}" >> $GITHUB_ENV
        fi

      env:
        REPO: ${{ github.event.repository.name }}
        OWNER: ${{ github.repository_owner }}
        TITLE: ${{ inputs.title }}

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      shell: bash
      run: |
        DEPS=(
          mike                                # versioned MkDocs
          mkdocs-material                     # theme
          mkdocs-tooltips                     # tooltips
          mkdocs-include-markdown-plugin      # include parts of code files
          git+https://github.com/swissiety/LspLexer4Pygments.git  # syntax highlighting
        )
        pip install "${DEPS[@]}" ${ADDITIONAL_PIP_DEPENDENCIES}
      env:
        ADDITIONAL_PIP_DEPENDENCIES: ${{ inputs.pip_dependencies }}

    - name: replace "{{ git_latest_release }}" with latest release tag version (without leading v) in all .md files under docs-dir
      shell: bash
      run: sed -i 's\{{ git_latest_release }}\'$(git tag --sort=committerdate | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?(\+[a-zA-Z0-9]+)?$' | tail -1 | sed 's/^v//')'\g' ${{ inputs.docs-dir }}/**.md

    - name: Configure git user
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Fetch gh-pages branch
      shell: bash
      run: |
        git fetch origin gh-pages:${{ inputs.pages-branch }} || ( echo "gh-pages branch '${{ inputs.pages-branch }}' not found!"; exit 1 )

    - name: Deploy the Preview
      shell: bash
      run: mike deploy --branch ${{ inputs.pages-branch }} --push --update-aliases -t "${{ env.title }}" ${{ env.name }}

    - name: summarize changed files to create links to the updated pages
      if: inputs.enable-comment == 'true' && github.event.action != 'closed'
      shell: bash
      id: diff
      run: |
        # sanity checks        
        if [[ ! -d "${LATEST_DIR}" ]]; then
          echo "summary=This seems to be the first version of the documentation - no documentation found for '${LATEST_DIR}'." >> $GITHUB_OUTPUT
          exit 0;
        elif [[ ! -d "${{ env.name }}" ]]; then
          echo "summary=No documentation found for preview '${{ env.name }}'" >> $GITHUB_OUTPUT
          exit 0;
        fi

        DIFF=$(diff -qr "${LATEST_DIR}" "${{ env.name }}" | grep '\.html')
        
        // debug
        echo "latestdir: ${LATEST_DIR}"
        echo "envname: ${{ env.name }}"
        echo $DIFF;
        
        
        CHANGES=""
        ADDITIONS=""
        DELETIONS=""
        
        # Sort files into categories
        while IFS= read -r line; do
          
          // debug
          echo $line
          
          if [[ $line == Files* ]]; then
            # Modified file
            PATH=$(echo "$line" | sed -E "s|.* and ${{ env.name }}/(.*) differ|\1|")
            URL="${{ env.base_url }}/${PATH}"
            CHANGES+="- [${PATH}](${URL})\n"
          elif [[ $line == Only\ in\ ${{ env.name }}:* ]]; then
            # Added file
            PATH=$(echo "$line" | sed -E "s|Only in ${{ env.name }}: ||")
            URL="${{ env.base_url }}/${PATH}"
            ADDITIONS+="- [${PATH}](${URL})\n"
          elif [[ $line == Only\ in\ ${LATEST_DIR}:* ]]; then
            # Deleted file
            PATH=$(echo "$line" | sed -E "s|Only in ${LATEST_DIR}: ||")
            DELETIONS+="- ~${PATH}~ \n"
          fi
        done <<< "$DIFF"
        
        # Create summary  
        {
          echo "summary<<EOF"
          [[ -n "$ADDITIONS" ]] && echo -e "*New*\n$ADDITIONS\n"
          [[ -n "$CHANGES" ]]   && echo -e "*Modified*\n$CHANGES\n"
          [[ -n "$DELETIONS" ]] && echo -e "*Deleted*\n$DELETIONS\n"
          echo "EOF"
        }
# >> $GITHUB_OUTPUT

      env:
        LATEST_DIR: ${{ inputs.latest-directory }}

    - name: Comment Link to Preview
      if: inputs.enable-comment == 'true' && github.event.action != 'closed'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          Documentation was updated: [Preview](${{ env.base-url }}/${{ env.name }}/)

#          ${{ steps.diff.outputs.summary || 'No content changes found. Likely a change in design,js etc.\n' }}

    - name: Delete the Preview
      if: github.event.action == 'closed'
      shell: bash
      run: mike delete --push ${{ env.name }}
