name: Documentation Deployment
description: Deploy documentation snapshots and releases to GitHub pages

inputs:
  version:
    description: 'Version of the deployed artifact '
    required: true
  pages-branch:
    description: 'The branch name where the gh pages are deployed to (default: gh-pages)'
    required: false
    default: 'gh-pages'

runs:
  using: composite
  steps:
    - name: Configuration
      shell: bash
      run: |
        echo 'base-url="https://$OWNER.github.io/$REPO/"'

      env:
        REPO: ${{ github.event.repository.name }}
        OWNER: ${{ github.repository_owner }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install Dependencies
      shell: bash
      # hint: keep synchronized with pr-preview
      run: |
        pip install \
        mike==1.1.2 \                                                    # versioned mkdocs
        mkdocs-material==9.5.13 \                                        # theme
        mkdocs-tooltips==0.4.0 \                                         # tooltips
        mkdocs-include-markdown-plugin==4.0.4 \                          # include (parts) of other files
        git+https://github.com/swissiety/LspLexer4Pygments.git           # syntax highlighting via lsp server

    - name: Configure git user
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Deploy the Documentation
      shell: bash
      run: mike deploy --branch ${{ inputs.pages-branch }} --push -t "${{ inputs.version }}" ${{ inputs.version }}
