name: Documentation Deployment
description: Deploy documentation snapshots and releases to GitHub pages

inputs:
  version:
    description: 'Version of the deployed artifact '
    required: true
  pages-branch:
    description: 'The branch name where the gh pages are deployed to (default: gh-pages)'
    required: false
    default: 'gh-pages'

runs:
  using: composite
  steps:
    - name: Configuration
      shell: bash
      run: |
        echo "base-url=https://${OWNER}.github.io/${REPO}/" >> $GITHUB_ENV

      env:
        REPO: ${{ github.event.repository.name }}
        OWNER: ${{ github.repository_owner }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      shell: bash
      run: |
        curl -H "Authorization: Bearer $GH_TOKEN" \
             -H "Accept: application/vnd.github.v3.raw" \
             -L \
             https://api.github.com/repos/secure-software-engineering/actions/contents/documentation/requirements.txt \
        | pip install -r /dev/stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure git user
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Deploy the Documentation
      shell: bash
      run: mike deploy --branch ${{ inputs.pages-branch }} --push -t "${{ inputs.version }}" ${{ inputs.version }}
